services:
  mongodb:
    image: mongo:8.0.0-rc20
    container_name: mongodb
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    volumes:
      - ./database/data_volumes:/data/db
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - internal_network
    expose:
      - "27017"
  backend:
    build: ./backend
    container_name: backend
    networks:
      - internal_network
    expose:
      - "5000"
    environment:
      MONGO_URI: mongodb://backend:password@mongodb:27017/data
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_BACKEND_URL: http://backend:5000
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - internal_network
    depends_on:
      - backend

networks:
  internal_network:
    driver: bridge